"""Metaphysical research feature package.

This package separates:
- calendar / ganzhi calculation
- astro longitude calculation
- derived trigger signals
- service helpers and feature builders

The legacy ``src.models.metaphysical_features`` module re-exports the public
APIs from here for backward compatibility.
"""

from .astro import (
    get_body_helio_lon,
    get_pluto_lon,
    get_sun_geo_lon,
    batch_planet_lons,
)
from .adapter import (
    attach_metaphysical_features,
    attach_next_production_metaphysical_features,
    finalize_next_production_candidate_frame,
)
from .calendar import get_ganzhi, batch_ganzhi
from .explainer import summarize_trigger_frame, summarize_trigger_row
from .feature_sets import (
    ASTRO_LONGITUDE_FEATURES,
    ASTRO_PHASE_FEATURES,
    AUTHOR_TIMING_FEATURES,
    CALENDAR_CYCLE_FEATURES,
    CURRENT_PRODUCTION_CANDIDATE_FEATURES,
    EXPERIMENTAL_AUTHOR_CANDIDATE_FEATURES,
    LONG_CYCLE_FEATURES,
    MACRO_EVENT_METAPHYSICAL_FEATURES,
    NEXT_PRODUCTION_CANDIDATE_FEATURES,
    NEXT_PRODUCTION_WEIGHTED_CANDIDATE_FEATURES,
    QUANT_FEATURES,
    REGIME_WEIGHTED_AUTHOR_FEATURES,
    RESONANCE_FEATURES,
    RESONANCE_PLUS_FEATURES,
    SELECTED_TRIGGER_FEATURES,
    SLIM_AUTHOR_CANDIDATE_FEATURES,
    TRIGGER_FEATURES,
    legacy_astro_columns,
    legacy_xuanxue_columns,
)
from .regime import (
    AUTHOR_FEATURE_REGIME_WEIGHTS,
    AUTHOR_REGIME_CUTOFF,
    apply_author_regime_weights,
    author_feature_weight,
    batch_author_regimes,
    classify_author_regime,
    infer_dynamic_author_regimes,
)
from .gann import extract_key_gann_levels, gann_square_of_9, gann_time_square
from .learning import (
    backfill_learning_snapshot_outcomes,
    build_daily_learning_snapshot,
    build_metaphysical_accuracy_dashboard,
    build_governance_run_record,
    build_lifecycle_run_record,
    build_stage_performance_record,
    build_daily_governance_summary,
    build_feishu_push_accuracy_dashboard,
    build_weekly_governance_summary,
    build_version_switch_change_request,
    build_version_switch_confirmation_draft,
    build_version_switch_execution_plan,
    build_version_switch_proposal,
    compute_learning_outcomes_from_prices,
    build_training_run_record,
    evaluate_governance_action,
    evaluate_candidate_promotion_readiness,
    evaluate_governance_stage_flow,
    evaluate_release_lifecycle,
    evaluate_stage_promotion_readiness,
    evaluate_stage_guardrail,
    latest_governance_run,
    latest_lifecycle_run,
    latest_stage_performance_run,
    latest_version_switch_proposal,
    render_daily_governance_summary,
    render_feishu_push_accuracy_dashboard,
    render_metaphysical_accuracy_dashboard,
    render_weekly_governance_summary,
    record_daily_learning_snapshot,
    record_governance_run,
    record_lifecycle_run,
    record_stage_performance_run,
    record_version_switch_proposal,
    record_training_run,
    select_matured_learning_samples,
    summarize_stage_performance_window,
    summarize_training_run_window,
)
from .model_backtest import (
    apply_tactical_report_signal_overlay,
    apply_next_production_position_sizing,
    build_next_production_signal_frame,
    latest_cached_next_production_signal,
    latest_next_production_signal,
    latest_next_production_signal_with_report_overlay,
    next_production_probability_cache_path,
    resolve_next_production_model_params,
    summarize_next_production_position_sizing,
)
from .report_ingest import (
    assess_tactical_report_freshness,
    archive_tactical_report_text,
    build_tactical_report_optimization_notes,
    compare_tactical_report_to_model_signal,
    detect_tactical_report_duplicates,
    detect_tactical_report_archive_duplicates,
    extract_tactical_report_date_iso,
    parse_tactical_report_text,
    sync_tactical_report_cache,
    sync_tactical_report_text,
    tactical_report_text_hash,
)
from .model_defaults import NEXT_PRODUCTION_MODEL_DEFAULTS, get_next_production_model_defaults
from .resonance import build_next_production_backtest_features, build_resonance_backtest_features
from .service import (
    build_metaphysical_features,
    build_metaphysical_features_if_enabled,
    dependencies_available,
)
from .signals import compute_triggers, is_hard_aspect, is_soft_aspect
from .strategy import generate_resonance_strategy_summary
from .theory_compare import get_author_theory_catalog, summarize_author_theory_coverage
from .time_law import mars_events_in_range, solar_term_date, solar_terms_in_range, ten_gods_for, year_ganzhi
from .time_law import (
    anniversary_cycle_distance,
    batch_long_cycle_features,
    nearest_lunar_phase_distance,
    saturn_jupiter_cycle_distance,
    solar_term_distance,
    uranus_cycle_distance,
    uranus_retrograde_state,
)
from .trend_law import (
    bb_breakout_strength,
    batch_month_turning_points,
    bollinger_bands,
    bollinger_state,
    is_bb_breakout,
    is_bb_squeeze,
    is_triple_resonance,
    is_volatility_plus_signal,
    month_turning_point_score,
    triple_resonance_score,
    volatility_plus_score,
)
from .warehouse import (
    DATASET_SNAPSHOTS_DIR,
    LEDGER_DIR,
    PRICE_HISTORY_DIR,
    WAREHOUSE_ROOT,
    archive_candidate_dataset,
    archive_price_history,
    ensure_metaphysical_warehouse,
)

__all__ = [
    "batch_ganzhi",
    "batch_planet_lons",
    "attach_metaphysical_features",
    "attach_next_production_metaphysical_features",
    "finalize_next_production_candidate_frame",
    "anniversary_cycle_distance",
    "batch_long_cycle_features",
    "ASTRO_LONGITUDE_FEATURES",
    "ASTRO_PHASE_FEATURES",
    "AUTHOR_TIMING_FEATURES",
    "build_metaphysical_features",
    "build_metaphysical_features_if_enabled",
    "build_next_production_backtest_features",
    "build_resonance_backtest_features",
    "bb_breakout_strength",
    "batch_month_turning_points",
    "bollinger_bands",
    "bollinger_state",
    "CALENDAR_CYCLE_FEATURES",
    "CURRENT_PRODUCTION_CANDIDATE_FEATURES",
    "EXPERIMENTAL_AUTHOR_CANDIDATE_FEATURES",
    "LONG_CYCLE_FEATURES",
    "is_bb_breakout",
    "is_bb_squeeze",
    "is_triple_resonance",
    "is_volatility_plus_signal",
    "month_turning_point_score",
    "triple_resonance_score",
    "volatility_plus_score",
    "WAREHOUSE_ROOT",
    "PRICE_HISTORY_DIR",
    "DATASET_SNAPSHOTS_DIR",
    "LEDGER_DIR",
    "archive_price_history",
    "archive_candidate_dataset",
    "ensure_metaphysical_warehouse",
    "compute_triggers",
    "dependencies_available",
    "extract_key_gann_levels",
    "gann_square_of_9",
    "gann_time_square",
    "build_daily_learning_snapshot",
    "build_metaphysical_accuracy_dashboard",
    "build_governance_run_record",
    "build_lifecycle_run_record",
    "build_stage_performance_record",
    "build_daily_governance_summary",
    "build_feishu_push_accuracy_dashboard",
    "build_weekly_governance_summary",
    "build_version_switch_change_request",
    "build_version_switch_confirmation_draft",
    "build_version_switch_execution_plan",
    "build_version_switch_proposal",
    "backfill_learning_snapshot_outcomes",
    "compute_learning_outcomes_from_prices",
    "build_training_run_record",
    "evaluate_governance_action",
    "evaluate_candidate_promotion_readiness",
    "evaluate_governance_stage_flow",
    "evaluate_release_lifecycle",
    "evaluate_stage_promotion_readiness",
    "evaluate_stage_guardrail",
    "latest_governance_run",
    "latest_lifecycle_run",
    "latest_stage_performance_run",
    "latest_version_switch_proposal",
    "render_daily_governance_summary",
    "render_feishu_push_accuracy_dashboard",
    "render_metaphysical_accuracy_dashboard",
    "render_weekly_governance_summary",
    "apply_next_production_position_sizing",
    "apply_tactical_report_signal_overlay",
    "build_next_production_signal_frame",
    "latest_cached_next_production_signal",
    "latest_next_production_signal",
    "latest_next_production_signal_with_report_overlay",
    "next_production_probability_cache_path",
    "assess_tactical_report_freshness",
    "archive_tactical_report_text",
    "build_tactical_report_optimization_notes",
    "compare_tactical_report_to_model_signal",
    "detect_tactical_report_archive_duplicates",
    "detect_tactical_report_duplicates",
    "extract_tactical_report_date_iso",
    "parse_tactical_report_text",
    "sync_tactical_report_cache",
    "sync_tactical_report_text",
    "tactical_report_text_hash",
    "record_daily_learning_snapshot",
    "record_governance_run",
    "record_lifecycle_run",
    "record_stage_performance_run",
    "record_version_switch_proposal",
    "record_training_run",
    "select_matured_learning_samples",
    "summarize_stage_performance_window",
    "resolve_next_production_model_params",
    "summarize_training_run_window",
    "summarize_next_production_position_sizing",
    "NEXT_PRODUCTION_MODEL_DEFAULTS",
    "get_next_production_model_defaults",
    "get_body_helio_lon",
    "get_ganzhi",
    "get_pluto_lon",
    "get_sun_geo_lon",
    "is_hard_aspect",
    "is_soft_aspect",
    "legacy_astro_columns",
    "legacy_xuanxue_columns",
    "MACRO_EVENT_METAPHYSICAL_FEATURES",
    "NEXT_PRODUCTION_CANDIDATE_FEATURES",
    "NEXT_PRODUCTION_WEIGHTED_CANDIDATE_FEATURES",
    "generate_resonance_strategy_summary",
    "mars_events_in_range",
    "QUANT_FEATURES",
    "REGIME_WEIGHTED_AUTHOR_FEATURES",
    "RESONANCE_FEATURES",
    "RESONANCE_PLUS_FEATURES",
    "SELECTED_TRIGGER_FEATURES",
    "SLIM_AUTHOR_CANDIDATE_FEATURES",
    "AUTHOR_FEATURE_REGIME_WEIGHTS",
    "AUTHOR_REGIME_CUTOFF",
    "apply_author_regime_weights",
    "author_feature_weight",
    "batch_author_regimes",
    "classify_author_regime",
    "infer_dynamic_author_regimes",
    "nearest_lunar_phase_distance",
    "saturn_jupiter_cycle_distance",
    "solar_term_date",
    "solar_term_distance",
    "solar_terms_in_range",
    "summarize_trigger_frame",
    "summarize_trigger_row",
    "get_author_theory_catalog",
    "summarize_author_theory_coverage",
    "ten_gods_for",
    "TRIGGER_FEATURES",
    "uranus_cycle_distance",
    "uranus_retrograde_state",
    "year_ganzhi",
]
